### ISSUE TITLE
While running, no ideal outcome occurred

### ISSUE THREAD

**Issue by YANGGANG1971** [vvv-school/tutorial_yarp-ports#1]
I added the following codes in tutorial-yarp-ports/port/main.cpp

```c++
    Port outPort;
    if (!outPort.open("/relay/out")) {
        yError() << "cannot open the output port";
        return -1;
    }
```

And then complied, everything seems ok.
But following the instructions, 

```sh
$ ./tutorial_yarp-port
$ yarp write /w
$ yarp read /r
$ yarp connect /w /relay/in
$ yarp connect /relay/out /r
$ yarp connect /relay/out /relay/in
```

When I typed some strings in the terminal where “yarp write /w”,  I did not see any output in the terminal where “yarp read /r”.
![image](https://user-images.githubusercontent.com/55526431/68824392-126d1f80-06da-11ea-8de3-f7bd88a79e14.png)
![image](https://user-images.githubusercontent.com/55526431/68824399-1731d380-06da-11ea-8ea2-4b80d4f69e00.png)

**Comment by pattacini** [comment]
Hi @YANGGANG1971 

This is a particular tutorial where the solution is not in the branch `master` but rather in the branch `solution`, as stated in the `README.md`.

However, the branch `solution` is up-to-date with the latest changes in the ecosystem, thus you won't be able to check out the `vvv18` tag for it, unfortunately. As a result, you'll get in trouble while building `solution` within the VM, unless you'll consider using Gitpod.

**Comment by YANGGANG1971** [comment]
Thank you. It does work. 
But, I am confusing that the revised codes are to build a connection between /relay/out and /relay/in, if I understand right.

I just used the command line to build a connection as follows.

    $ yarp connect /relay/out /relay/in 

Why cannot it work?

**Comment by pattacini** [comment]
Don't make the connection `/relay/out` ➡️ `/relay/in`. The purpose of the tutorial is to cut the direct connection `/w` ➡️ `/r` and establish a "_man in the middle_" (relay). 

Further, `/relay/out` ➡️ `/relay/in` does not make any sense as it would imply to connect the output of the relay to its input, where the output is already the straight copy of the input.
